artifact_uri: file:///C:/Users/Professional/Documents/NLP/bow-mlp/executor/mlruns/0/10b18bafdf5f4209bb99ac043e16aa7f/artifacts
end_time: 1633099134120
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 10b18bafdf5f4209bb99ac043e16aa7f
run_uuid: 10b18bafdf5f4209bb99ac043e16aa7f
source_name: ''
source_type: 4
source_version: ''
start_time: 1633096358724
status: 3
tags: []
user_id: Professional
