artifact_uri: file:///C:/Users/Professional/Documents/NLP/bow-mlp/executor/mlruns/0/2eafb34f600e49a9bb351179fb54b9d3/artifacts
end_time: 1633092735274
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 2eafb34f600e49a9bb351179fb54b9d3
run_uuid: 2eafb34f600e49a9bb351179fb54b9d3
source_name: ''
source_type: 4
source_version: ''
start_time: 1633091688720
status: 3
tags: []
user_id: Professional
